<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form General jurnal</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td>សាខា</td>
							<td><?php echo $frm->getElement('brance')?></td>
							<td>Add_Date</td>
							<td><?php echo $frm->getElement('add_date')?></td>	
							<td>Account_Number</td>
							<td><?php echo $frm->getElement('account_number')?></td>
							
						</tr>
						<tr>
							<td>Parents Account</td>
							<td><?php echo $frm->getElement('parent')?></td>
							<td>Account_name</td>
							<td><input id="account_name" /><?php //echo $frm->getElement('account_name')?></td>
							<td>Note</td>
							<td><?php echo $frm->getElement('note');?></td>
							
						</tr>
						<tr>
							
							<td>Debit</td>
							<td><?php echo $frm->getElement('debit')?></td>
							<td>Cradit</td>
							<td><?php echo $frm->getElement('credit');?></td>
							<td></td>
							<td></td>
						</tr>
						
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");

var account_store  = getDataStorefromJSON('id','name',[]);
require(["dojo/ready"], function(ready){
	 ready(function(){
		
	  });
	new dijit.form.FilteringSelect({
	store: account_store,
	autoComplete: true,      
	required: false,		           
	name: "account_name",
	id: "account_name",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
      }
	}, "account_name");

	});
var url_getaccount = '<?php echo $this->url(array('module'=>'accounting','controller'=>'generaljurnal','action'=>'get-accountname')); ?>';
function getAllAccountNameByParents(){
	 parent_id = dijit.byId('parent').get('value');
	if(parent_id==-1){
		return false;
	}
	dojo.xhrPost({
		url:url_getaccount,	
		content:{ 
		    'parent':parent_id
		},		    
		handleAs:"json",
		load: function(data) {
		   account_store  = getDataStorefromJSON('id','name', data);		
		   dijit.byId('account_name').set('store', account_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>